name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Workload Identity Federation
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: "projects/826773862580/locations/global/workloadIdentityPools/github/providers/github"
          service_account: "firebase-deployer@selahgpt.iam.gserviceaccount.com"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: List files in workspace
        run: ls -la ${{ github.workspace }}

      - name: Upload workspace contents
        uses: actions/upload-artifact@v4
        with:
          name: workspace-files
          path: ./

      - name: Deploy to Firebase
        working-directory: ${{ github.workspace }}
        run: firebase deploy --only functions
