name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Firebase Functions
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Workload Identity Federation
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}

      - name: Install dependencies
        run: cd functions && npm install

      - name: Deploy to Firebase
        run: firebase deploy --only functions
